#! /bin/bash

set -e
set -x

apt-get remove --purge pocl-opencl-icd
apt autoremove

BUILD_PATH=/opt
INSTALL_PATH=/opt/pocl-master-build

rm -Rf "$INSTALL_PATH"
rm -Rf "$BUILD_PATH/pocl-master"
cd /opt
git clone https://github.com/pocl/pocl.git pocl-master
cd "$BUILD_PATH/pocl-master"
git checkout master

PATCHFILE=/tmp/pocl-fix-macros.patch 

cat > $PATCHFILE <<EOF
diff --git a/lib/kernel/vecmathlib/floattypes.h b/lib/kernel/vecmathlib/floattypes.h
index fa4cc44..cb9071b 100644
--- a/lib/kernel/vecmathlib/floattypes.h
+++ b/lib/kernel/vecmathlib/floattypes.h
@@ -40,6 +40,7 @@ using namespace std;
 #endif
 
 // Capture libc macros, then undefine them
+/*
 #ifndef isfinite
 #error "isfinite is not a macro"
 #endif
@@ -55,6 +56,7 @@ using namespace std;
 #ifndef signbit
 #error "signbit is not a macro"
 #endif
+*/
 
 namespace {
 template <typename T> inline int libc_isfinite(T x) { return isfinite(x); }
EOF

patch -p1 < $PATCHFILE

rm -f $PATCHFILE

mkdir "$BUILD_PATH/pocl-master/build"
(cd "$BUILD_PATH/pocl-master/build" && \
	cmake \
		-D CMAKE_INSTALL_PREFIX="$INSTALL_PATH" \
		-D POCL_INSTALL_ICD_VENDORDIR="$INSTALL_PATH" \
		-D LLVM_CONFIG=/opt/llvm-4.0-build/bin/llvm-config \
		-D CMAKE_BUILD_TYPE=Release \
		.. &&  \
	make -j10 install)

