#! /bin/bash

set -e
set -x

apt-get remove --purge pocl-opencl-icd
apt autoremove

if test "$1" = ""; then
  echo "usage: $0 branch"
  exit 1
fi

BRANCH="$1"

BUILD_PATH="/opt/pocl-$BRANCH-build"
INSTALL_PATH="/opt/pocl-$BRANCH"

rm -Rf "$INSTALL_PATH"
rm -Rf "$BUILD_PATH/pocl-master"

/shared/config/build-llvm-4.0 "$INSTALL_PATH"

cd /opt
git clone https://github.com/pocl/pocl.git "$BUILD_PATH"
cd "$BUILD_PATH"
git checkout "$BRANCH"

PATCHFILE=/tmp/pocl-fix-macros.patch 

cat > $PATCHFILE <<EOF
diff --git a/lib/kernel/vecmathlib/floattypes.h b/lib/kernel/vecmathlib/floattypes.h
index fa4cc44..cb9071b 100644
--- a/lib/kernel/vecmathlib/floattypes.h
+++ b/lib/kernel/vecmathlib/floattypes.h
@@ -40,6 +40,7 @@ using namespace std;
 #endif
 
 // Capture libc macros, then undefine them
+/*
 #ifndef isfinite
 #error "isfinite is not a macro"
 #endif
@@ -55,6 +56,7 @@ using namespace std;
 #ifndef signbit
 #error "signbit is not a macro"
 #endif
+*/
 
 namespace {
 template <typename T> inline int libc_isfinite(T x) { return isfinite(x); }
EOF

patch -p1 < $PATCHFILE

rm -f $PATCHFILE

mkdir "$BUILD_PATH/build"
(cd "$BUILD_PATH/build" && \
	cmake \
		-D CMAKE_INSTALL_PREFIX="$INSTALL_PATH" \
		-D POCL_INSTALL_ICD_VENDORDIR="$INSTALL_PATH" \
		-D LLVM_CONFIG=$INSTALL_PATH/bin/llvm-config \
		-D CMAKE_BUILD_TYPE=Release \
		.. &&  \
	make -j30 install)

