#! /bin/bash

set -e

USE_LLVM_PACKAGES=1

if test "$1" = "--do-not-use-llvm-packages"; then
  USE_LLVM_PACKAGES=0
  shift
fi

set -x

apt-get remove --purge pocl-opencl-icd libpocl2 libpocl2-common
apt autoremove
apt install libhwloc-dev libz-dev cmake pkgconf ocl-icd-dev

POCL_BRANCH="$1"
LLVM_VERSION="$2"

POCL_GIT_URL="https://github.com/pocl/pocl.git"
# POCL_GIT_URL="/home/andreas/pack/pocl"
if test -c /dev/nvidiactl; then
  POCL_EXTRA_FLAGS="-DENABLE_CUDA=ON"
else
  POCL_EXTRA_FLAGS=""
fi

if test "$POCL_BRANCH" = ""; then
  POCL_BRANCH="release_4_0"
fi
if test "$LLVM_VERSION" = ""; then
  LLVM_VERSION=16
fi

BUILD_PATH="/opt/pocl-$POCL_BRANCH-build"
INSTALL_PATH="/opt/pocl-$POCL_BRANCH"

EXECUTABLE="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$EXECUTABLE")"
SCRIPT_DIR="$(readlink -f "$SCRIPT_DIR")"

rm -Rf "$INSTALL_PATH"
rm -Rf "$BUILD_PATH"

if [[ "$USE_LLVM_PACKAGES" = 1 ]]; then
  apt install llvm-$LLVM_VERSION-dev libclang-$LLVM_VERSION-dev clang-$LLVM_VERSION libclang-cpp$LLVM_VERSION-dev libomp5-$LLVM_VERSION
  LLVM_CONFIG="/usr/bin/llvm-config-$LLVM_VERSION"
else
  $SCRIPT_DIR/build-llvm-$LLVM_VERSION "$INSTALL_PATH"
  LLVM_CONFIG="$INSTALL_PATH/bin/llvm-config"
fi

cd /opt
git clone --depth 1 "$POCL_GIT_URL" "$BUILD_PATH" -b "$POCL_BRANCH"
cd "$BUILD_PATH"

if test "$POCL_BRANCH" = "release_3_0"; then
  curl https://patch-diff.githubusercontent.com/raw/pocl/pocl/pull/1067.diff | filterdiff -p 1 -x CHANGES | patch -p1
  curl https://patch-diff.githubusercontent.com/raw/pocl/pocl/pull/1069.diff | patch -p1
fi
if test "$POCL_BRANCH" = "release_3_1"; then
  # https://github.com/pocl/pocl/issues/1157
  curl https://github.com/franz/pocl/commit/50c40baa28a97d89ff2533732e4118d273e95eb1.diff | patch -p1
fi

mkdir "$BUILD_PATH/build"
(cd "$BUILD_PATH/build" && \
        cmake \
                -D CMAKE_INSTALL_PREFIX="$INSTALL_PATH" \
                -D POCL_INSTALL_ICD_VENDORDIR="$INSTALL_PATH" \
                -D LLVM_CONFIG=$LLVM_CONFIG \
                -D CMAKE_BUILD_TYPE=Release \
                $POCL_EXTRA_FLAGS \
                .. &&  \
        make -j15 install)

# -D LLC_HOST_CPU=haswell for compatibility with valgrind

# delete other POCL ICD files, to avoid conflicts
rm -f /etc/OpenCL/vendors/pocl*.icd

echo "$INSTALL_PATH/lib/libpocl.so" > /etc/OpenCL/vendors/pocl-$POCL_BRANCH.icd

# vim: sw=2
