#! /bin/bash

set -e

USE_LLVM_PACKAGES=1

if test "$1" = "--do-not-use-llvm-packages"; then
  USE_LLVM_PACKAGES=0
  shift
fi

set -x

apt-get remove --purge pocl-opencl-icd libpocl2 libpocl2-common
apt autoremove
apt install libhwloc-dev libz-dev cmake pkg-config

POCL_BRANCH="$1"
LLVM_VERSION="$2"

POCL_GIT_URL="https://github.com/isuruf/pocl.git"
if test "$POCL_BRANCH" = ""; then
	POCL_BRANCH="1.5_and_patches"
fi
if test -c /dev/nvidiactl; then
	POCL_EXTRA_FLAGS="-DENABLE_CUDA=ON"
else
	POCL_EXTRA_FLAGS=""
fi

if test "$LLVM_VERSION" = ""; then
  LLVM_VERSION=10
fi

BUILD_PATH="/opt/pocl-$POCL_BRANCH-build"
INSTALL_PATH="/opt/pocl-$POCL_BRANCH"

EXECUTABLE="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$EXECUTABLE")"
SCRIPT_DIR="$(readlink -f "$SCRIPT_DIR")"

rm -Rf "$INSTALL_PATH"
rm -Rf "$BUILD_PATH"

if [[ "$USE_LLVM_PACKAGES" = 1 ]]; then
  apt install libclang-$LLVM_VERSION-dev clang-$LLVM_VERSION libclang-cpp$LLVM_VERSION-dev
  LLVM_CONFIG="/usr/bin/llvm-config-$LLVM_VERSION"
else
  $SCRIPT_DIR/build-llvm-$LLVM_VERSION "$INSTALL_PATH"
  LLVM_CONFIG="$INSTALL_PATH/bin/llvm-config"
fi

cd /opt
git clone "$POCL_GIT_URL" "$BUILD_PATH"
cd "$BUILD_PATH"
git checkout "$POCL_BRANCH"

# https://github.com/pocl/pocl/issues/757#issuecomment-655275263
cat > par-meta.diff <<EOF
diff --git a/lib/llvmopencl/ParallelRegion.cc b/lib/llvmopencl/ParallelRegion.cc
index 187e8b52..4a635377 100644
--- a/lib/llvmopencl/ParallelRegion.cc
+++ b/lib/llvmopencl/ParallelRegion.cc
@@ -474,7 +474,14 @@ void ParallelRegion::AddParallelLoopMetadata(llvm::MDNode *Identifier) {
     for (BasicBlock::iterator ii = bb->begin(), ee = bb->end();
          ii != ee; ii++) {
 
-      if (ii->mayReadOrWriteMemory()) {
+      if (ii->mayReadFromMemory()) {
+        // Parallel loop metadata on memory reads also implies that
+        // if-conversion (i.e., speculative execution within a loop
+        // iteration) is safe. This isn't guaranteed.
+        continue;
+      }
+
+      if (ii->mayWriteToMemory()) {
         MDNode *NewMD = MDNode::get(bb->getContext(), Identifier);
         MDNode *OldMD = ii->getMetadata(PARALLEL_MD_NAME);
         if (OldMD != nullptr) {
EOF

patch -p1 < par-meta.diff

mkdir "$BUILD_PATH/build"
(cd "$BUILD_PATH/build" && \
	cmake \
		-D CMAKE_INSTALL_PREFIX="$INSTALL_PATH" \
		-D POCL_INSTALL_ICD_VENDORDIR="$INSTALL_PATH" \
		-D LLVM_CONFIG=$LLVM_CONFIG \
		-D CMAKE_BUILD_TYPE=Release \
		$POCL_EXTRA_FLAGS \
		.. &&  \
	make -j15 install)

# delete other POCL ICD files, to avoid conflicts
rm -f /etc/OpenCL/vendors/pocl*.icd

echo "$INSTALL_PATH/lib/libpocl.so" > /etc/OpenCL/vendors/pocl-$POCL_BRANCH.icd
